name: Python bindings CI

on:
  push:
    branches: [main]
  pull_request:
    paths:
      # When we change code that bindings depend on, we want to ensure that the maturin builds still work
      - crates/pixi-build-backend/**
      - Cargo.*

      # When something in the bindings themselves changes
      - py-pixi-build-backend/**

      # Or when this workflow changes
      - .github/workflows/python-bindings.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  PYTHONIOENCODING: utf-8

jobs:
  format_lint_test:
    name: Test the Python bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          submodules: recursive
      - uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7 # v0.9.3
        with:
          manifest-path: py-pixi-build-backend/pixi.toml
          environments: ci
      - name: Run clippy
        run: |
          cd py-pixi-build-backend
          pixi run -e ci lint
      - name: Run tests
        run: |
          cd py-pixi-build-backend
          pixi run -e ci test --color=yes
